"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let tab="dashboard";
const TOKEN_KEY="livinghub_admin_token";
const getToken=()=>sessionStorage.getItem(TOKEN_KEY)||"";
const labels={dashboard:["概览","查看当前会员、待审核发布和活动运营状态。"],submissions:["发布审核","任何有效 LivingHub 注册用户都可以提交；批准后才会进入公开地图。"],members:["会员管理","确认会员费、激活或暂停年度会员资格。"],plans:["会员方案","Basic 免费；Annual Member $299/年。活动费不进入平台账户。"],events:["活动管理","查看成团人数、截止时间、公开区域和活动状态。"],bookings:["活动报名","活动费由组织者直接收取；后台只记录报名与状态。"],posts:["内容发布","发布平台动态，不虚构人数、付款或成功案例。"],settings:["品牌与平台收款","这里只配置 LivingHub 自己的 Annual Member 年费收款。"]};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const dt=v=>v?new Date(v).toLocaleString("zh-CN"):"—";
async function api(url,opt={}){const token=getToken();const r=await fetch(url,{...opt,credentials:"same-origin",headers:{...(opt.body instanceof FormData?{}:{"Content-Type":"application/json"}),...(token?{Authorization:`Bearer ${token}`} : {}),...(opt.headers||{})}});const text=await r.text();let j={};try{j=text?JSON.parse(text):{}}catch{throw new Error("服务器返回格式异常")}if(r.status===401){if(url==="/api/admin/login")throw new Error("管理员邮箱或后台密码不正确");sessionStorage.removeItem(TOKEN_KEY);showLogin();throw new Error("登录已失效，请重新登录")}if(!r.ok)throw new Error(j.error||"操作失败");return j}
function showLogin(){
  const login=$("#login"),app=$("#app");
  login.hidden=false;login.style.display="grid";
  app.hidden=true;app.style.display="none";
}
function showApp(){
  const login=$("#login"),app=$("#app");
  login.hidden=true;login.style.display="none";
  app.hidden=false;app.style.display="grid";
}
function notice(msg,type="ok"){const n=document.createElement("div");n.className=`notice ${type}`;n.textContent=msg;document.body.append(n);setTimeout(()=>n.remove(),3000)}
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const msg=$("#loginMsg");msg.textContent="正在登录…";try{const login=await api("/api/admin/login",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});if(login.token)sessionStorage.setItem(TOKEN_KEY,login.token);const me=await api("/api/admin/me");$("#adminEmail").textContent=me.email;showApp();await setTab("dashboard");msg.textContent=""}catch(err){msg.innerHTML=`<div class="notice error">${esc(err.message)}</div>`}});
$("#logout").addEventListener("click",async()=>{try{await api("/api/admin/logout",{method:"POST"})}finally{sessionStorage.removeItem(TOKEN_KEY);showLogin()}});
$$('[data-tab]').forEach(b=>b.addEventListener("click",()=>setTab(b.dataset.tab)));
async function setTab(next){tab=next;$$('[data-tab]').forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));$("#title").textContent=labels[tab][0];$("#sub").textContent=labels[tab][1];$("#panel").innerHTML='<div class="loading">正在加载…</div>';try{await ({dashboard,submissions,members,plans,events,bookings,posts,settings}[tab])($("#panel"))}catch(err){$("#panel").innerHTML=`<div class="notice error">${esc(err.message)}</div>`}}
async function dashboard(p){const d=await api('/api/admin/dashboard');p.innerHTML=`<div class="metric-grid"><article><small>有效注册</small><strong>${d.members.active||0}</strong></article><article><small>Annual会员费待确认</small><strong>${d.members.payment_pending||0}</strong></article><article><small>待审核活动</small><strong>${d.pending_submissions||0}</strong></article><article><small>未来活动</small><strong>${d.upcoming_events||0}</strong></article><article><small>已成团</small><strong>${d.formed_events||0}</strong></article></div><div class="info-card"><h2>当前资金路径</h2><p><b>Basic：</b>免费注册，可以报名普通活动，也可以提交活动。</p><p><b>Annual Member：</b>$299/年，由 LivingHub 收取。</p><p><b>每场活动费：</b>组织者自己定价、自己收款、自己退款、自负盈亏；LivingHub 前期不抽成、不代收。</p></div>`}
async function submissions(p){const rows=await api('/api/admin/submissions');p.innerHTML=`<div class="table-wrap"><table><thead><tr><th>审核编号</th><th>合作会员/组织者</th><th>活动</th><th>地区与时间</th><th>费用</th><th>状态</th><th>审核</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.submission_number)}</b><br><small>${esc(x.provenance_code||'')}</small></td><td>${esc(x.organizer_name)}<br><small>${esc(x.organizer_contact)}</small></td><td><b>${esc(x.title)}</b><br><small>${esc(x.description)}</small></td><td>${esc(x.city)}, ${esc(x.country)}<br>${esc(x.public_area)}<br><small>${dt(x.start_at)}</small></td><td>${esc(x.currency)} ${Number(x.price||0).toFixed(2)}<br>${esc(x.required_tier)}</td><td><span class="badge">${esc(x.status)}</span></td><td><textarea id="note-${x.id}" placeholder="审核备注">${esc(x.admin_note||'')}</textarea><div class="row"><button data-review="approved" data-id="${x.id}">批准并发布</button><button class="danger" data-review="rejected" data-id="${x.id}">拒绝</button></div></td></tr>`).join('')}</tbody></table></div>`;$$('[data-review]').forEach(b=>b.onclick=async()=>{await api(`/api/admin/submissions/${b.dataset.id}`,{method:'PATCH',body:JSON.stringify({status:b.dataset.review,admin_note:$(`#note-${b.dataset.id}`).value})});notice(b.dataset.review==='approved'?'已批准并进入公开活动':'已拒绝');setTab('submissions')})}
async function members(p){const rows=await api('/api/admin/members');p.innerHTML=`<div class="table-wrap"><table><thead><tr><th>会员</th><th>类型</th><th>联系</th><th>付款</th><th>有效期</th><th>操作</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.member_number)}</b><br>${esc(x.display_name)} · ${esc(x.age)}</td><td>${x.tier==='community'?'<span class="badge">Basic 免费</span>':x.tier==='select'?'<span class="badge partner">Annual $299</span>':'<span class="badge">Legacy</span>'}<br>${esc(x.plan_name)}</td><td>${esc(x.city)}<br>${esc(x.contact)}</td><td>${esc(x.status)}<br><small>${esc(x.payment_method)} ${esc(x.payment_reference)}</small></td><td>${dt(x.starts_at)}<br>${dt(x.expires_at)}</td><td><select id="ms-${x.id}">${['awaiting_payment','payment_pending','active','expired','suspended','cancelled','refunded'].map(v=>`<option ${x.status===v?'selected':''}>${v}</option>`).join('')}</select><input id="mr-${x.id}" value="${esc(x.payment_reference||'')}" placeholder="付款参考"><button data-member="${x.id}">保存</button>${x.photo?`<a href="/api/admin/members/${x.id}/photo" target="_blank">查看照片</a>`:''}</td></tr>`).join('')}</tbody></table></div>`;$$('[data-member]').forEach(b=>b.onclick=async()=>{await api(`/api/admin/members/${b.dataset.member}`,{method:'PATCH',body:JSON.stringify({status:$(`#ms-${b.dataset.member}`).value,payment_reference:$(`#mr-${b.dataset.member}`).value})});notice('会员已更新');setTab('members')})}
async function plans(p){const rows=await api('/api/admin/plans');p.innerHTML=`<div class="cards">${rows.map(x=>`<form class="edit-card" data-plan="${x.id}"><h2>${x.tier==='community'?'Basic 免费会员':x.tier==='select'?'Annual Member':'Legacy Plan'}</h2><div class="form-grid"><label>中文名称<input name="name_zh" value="${esc(x.name_zh)}"></label><label>英文名称<input name="name_en" value="${esc(x.name_en)}"></label><label>年度价格<input type="number" name="price" value="${x.price}"></label><label>有效天数<input type="number" name="duration_days" value="${x.duration_days}"></label></div><label>中文简介<textarea name="summary_zh">${esc(x.summary_zh)}</textarea></label><label>英文简介<textarea name="summary_en">${esc(x.summary_en)}</textarea></label><label>中文权益<textarea name="features_zh">${esc(x.features_zh)}</textarea></label><label>英文权益<textarea name="features_en">${esc(x.features_en)}</textarea></label><label>该方案 Stripe Payment Link<input name="stripe_url" value="${esc(x.stripe_url)}"></label><input type="hidden" name="sort_order" value="${x.sort_order}"><label class="check"><input type="checkbox" name="is_active" ${x.is_active?'checked':''}> 前台开放</label><button>保存方案</button></form>`).join('')}</div>`;$$('[data-plan]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(f));o.is_active=f.is_active.checked;await api(`/api/admin/plans/${f.dataset.plan}`,{method:'PATCH',body:JSON.stringify(o)});notice('会员方案已保存')})}
async function events(p){const rows=await api('/api/admin/events');p.innerHTML=`<form id="newEvent" class="edit-card"><h2>新增活动</h2>${eventFields({})}<button>创建活动</button></form><div class="cards">${rows.map(x=>`<form class="edit-card" data-event="${x.id}"><h2>${esc(x.title_zh)}</h2>${eventFields(x)}<div class="row"><button>保存</button><button type="button" class="danger" data-delete-event="${x.id}">删除</button></div></form>`).join('')}</div>`;$('#newEvent').onsubmit=async e=>{e.preventDefault();await api('/api/admin/events',{method:'POST',body:new FormData(e.currentTarget)});notice('活动已创建');setTab('events')};$$('[data-event]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();await api(`/api/admin/events/${f.dataset.event}`,{method:'PATCH',body:new FormData(f)});notice('活动已保存')});$$('[data-delete-event]').forEach(b=>b.onclick=async()=>{if(confirm('确认删除活动？')){await api(`/api/admin/events/${b.dataset.deleteEvent}`,{method:'DELETE'});setTab('events')}})}
function eventFields(x){return `<div class="form-grid"><label>中文标题<input name="title_zh" value="${esc(x.title_zh)}" required></label><label>英文标题<input name="title_en" value="${esc(x.title_en)}" required></label><label>时间<input type="datetime-local" name="start_at" value="${x.start_at?new Date(x.start_at).toISOString().slice(0,16):''}" required></label><label>报名截止<input type="datetime-local" name="deadline_at" value="${x.deadline_at?new Date(x.deadline_at).toISOString().slice(0,16):''}"></label><label>城市<input name="city" value="${esc(x.city||'Los Angeles')}" required></label><label>地区<input name="region" value="${esc(x.region||'CA')}"></label><label>国家<input name="country" value="${esc(x.country||'US')}"></label><label>时区<input name="timezone" value="${esc(x.timezone||'America/Los_Angeles')}"></label><label>公开区域<input name="public_venue" value="${esc(x.public_venue||'Greater Los Angeles')}"></label><label>具体地点（成团后开放）<input name="private_venue" value="${esc(x.private_venue)}"></label><label>最低成团人数<input type="number" min="2" name="min_participants" value="${x.min_participants||2}"></label><label>容量<input type="number" min="2" name="capacity" value="${x.capacity||10}"></label><label>单场费用<input type="number" step=".01" name="price" value="${x.price||0}"></label><label>货币<input name="currency" value="${esc(x.currency||'USD')}"></label><label>参加资格<select name="required_tier"><option value="community" ${x.required_tier==='community'?'selected':''}>Basic 免费注册</option><option value="select" ${x.required_tier==='select'?'selected':''}>Annual Member</option></select></label><label>活动状态<select name="event_status">${['recruiting','formed','full','cancelled_minimum','cancelled_organizer','completed'].map(v=>`<option ${x.event_status===v?'selected':''}>${v}</option>`).join('')}</select></label><label>封面图<input type="file" name="image" accept="image/*"></label><label class="check"><input type="checkbox" name="is_public" value="true" ${x.is_public!==false?'checked':''}> 公开显示</label></div><label>中文说明<textarea name="description_zh">${esc(x.description_zh)}</textarea></label><label>英文说明<textarea name="description_en">${esc(x.description_en)}</textarea></label><label>退款规则<textarea name="refund_policy">${esc(x.refund_policy||'')}</textarea></label>`}
async function bookings(p){const rows=await api('/api/admin/bookings');p.innerHTML=`<div class="table-wrap"><table><thead><tr><th>报名</th><th>会员</th><th>活动/金额</th><th>状态</th><th>地址与操作</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(x.booking_number)}</b><br><small>${dt(x.created_at)}</small></td><td>${esc(x.display_name)}<br>${esc(x.member_number)}<br>${esc(x.contact)}</td><td>${esc(x.title_zh||x.title_en)}<br>${esc(x.currency)} ${Number(x.amount_due||0).toFixed(2)}</td><td><select id="bs-${x.id}">${['awaiting_payment','payment_pending','payment_received','confirmed','venue_unlocked','checked_in','completed','cancelled','refunded'].map(v=>`<option ${x.status===v?'selected':''}>${v}</option>`).join('')}</select></td><td><input id="bv-${x.id}" value="${esc(x.private_venue||'')}" placeholder="具体地点"><input id="br-${x.id}" value="${esc(x.payment_reference||'')}" placeholder="付款参考"><button data-booking="${x.id}">保存</button></td></tr>`).join('')}</tbody></table></div>`;$$('[data-booking]').forEach(b=>b.onclick=async()=>{await api(`/api/admin/bookings/${b.dataset.booking}`,{method:'PATCH',body:JSON.stringify({status:$(`#bs-${b.dataset.booking}`).value,private_venue:$(`#bv-${b.dataset.booking}`).value,payment_reference:$(`#br-${b.dataset.booking}`).value})});notice('报名已更新');setTab('bookings')})}
async function posts(p){const rows=await api('/api/admin/posts');p.innerHTML=`<form id="postForm" class="edit-card"><h2>发布平台动态</h2><div class="form-grid"><label>类型<input name="post_type" value="club"></label><label>主题<input name="theme" value="community"></label><label>中文标题<input name="title_zh"></label><label>英文标题<input name="title_en"></label></div><label>中文内容<textarea name="content_zh" required></textarea></label><label>英文内容<textarea name="content_en"></textarea></label><label class="check"><input type="checkbox" name="is_public" checked> 公开</label><button>发布</button></form><div class="cards">${rows.map(x=>`<article class="edit-card"><small>${esc(x.theme)} · ${dt(x.created_at)}</small><h2>${esc(x.title_zh||x.title_en)}</h2><p>${esc(x.content_zh||x.content_en)}</p><button class="danger" data-delete-post="${x.id}">删除</button></article>`).join('')}</div>`;$('#postForm').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.currentTarget));o.is_public=e.currentTarget.is_public.checked;await api('/api/admin/posts',{method:'POST',body:JSON.stringify(o)});notice('内容已发布');setTab('posts')};$$('[data-delete-post]').forEach(b=>b.onclick=async()=>{await api(`/api/admin/posts/${b.dataset.deletePost}`,{method:'DELETE'});setTab('posts')})}
async function settings(p){const x=await api('/api/admin/settings');p.innerHTML=`<form id="settingsForm" class="edit-card"><h2>平台品牌与会员费收款</h2><div class="form-grid"><label>品牌名称<input name="brand_name" value="${esc(x.brand_name)}"></label><label>页面标题<input name="page_title" value="${esc(x.page_title)}"></label><label>首发市场<input name="city" value="${esc(x.city)}"></label><label>联系邮箱<input name="contact_email" value="${esc(x.contact_email)}"></label><label>网站地址<input name="site_url" value="${esc(x.site_url)}"></label><label>业务地址<input name="business_address" value="${esc(x.business_address)}"></label><label>平台默认 Stripe Link<input name="stripe_url" value="${esc(x.stripe_url)}"></label><label>Zelle 收款名称<input name="zelle_name" value="${esc(x.zelle_name)}"></label><label>Zelle 邮箱/电话<input name="zelle_contact" value="${esc(x.zelle_contact)}"></label><label>二维码说明<input name="qr_label" value="${esc(x.qr_label)}"></label><label>付款二维码<input type="file" name="qr_image" accept="image/*"></label></div><div class="info-card"><b>资金路径说明</b><p>这里只用于 LivingHub 自己的 Annual Member 年费。每一场用户组织的活动都有自己的收款方式，活动费直接付给组织者，平台前期不抽成。</p></div><button>保存设置</button></form>`;$('#settingsForm').onsubmit=async e=>{e.preventDefault();await api('/api/admin/settings',{method:'PATCH',body:new FormData(e.currentTarget)});notice('设置已保存')}}
(async()=>{try{const me=await api('/api/admin/me');$("#adminEmail").textContent=me.email;showApp();await setTab('dashboard')}catch{showLogin()}})();
